### ISSUE TITLE
Make plugin choose again, good and easy for you.

### ISSUE THREAD

**Issue by Cobradabest** [qwiglydee/anki-interactive#18]
I'm coming from Memrise, and this plugin makes switching to Anki very appealing, but what is keeping me from switching to Anki is it using the honour system, as in you have to tell the program how you did. The problem with that is that I don't trust myself to be honest, and always go easy or hard on myself.

Is it possible to make the plugin choose for you based on the answers you input?

**Comment by danieltomasz** [comment]
it is not you are looking, but I think this could interest you - fast review like memrise https://ankiweb.net/shared/info/1046608507

**Comment by qwiglydee** [comment]
Yes. It is theoretically possible.
But plugin cannot determine whether the answer was "hard" or "easy" for you.
Also, if it auto-press the button, you won't have time to overview the correct answer before going to next card.

So, no.
