### ISSUE TITLE
Invalid HTML on card

### ISSUE THREAD

**Issue by PrinceCuboid** [qwiglydee/anki-interactive#24]
Hello, 

Im a newbie newbie to Anki and even more its coding capabilities. This interactive add-on, however, seems to be the future of flashcards; it's just so amazing. I've had some trouble trying to get this to work for me, though. 

When I first download it and run it to Anki, I opened the practice demo to get an understanding of the layout. The first two cards work without a problem. However, it's the 3rd card: Interactive Cloze that giving me issues.  

Here is a screenshot of the warning:
<img width="854" alt="Screen Shot 2020-05-15 at 2 13 49 PM" src="https://user-images.githubusercontent.com/24395095/82088092-c023b000-96b6-11ea-93a6-5a7277a9897e.png">

Not knowing what to do, I located the code inside of Anki and just deleted it. Then I ran into the same problem; except this time for the back template. I deleted it from the back template as well. 

I ran into another problem after doing this:
<img width="1440" alt="Screen Shot 2020-05-15 at 2 21 06 PM" src="https://user-images.githubusercontent.com/24395095/82088412-522bb880-96b7-11ea-830b-ac12781811e5.png">

The front template is asking something about the HTML and the back template seems to be working fine. 

I'm using Anki 2.1. I read in the folder manual about ensuring that PythonPath has the Anki sources; I don't know what this means.

Any help would be much appreciated,

Thanks.

**Comment by aedangibson** [comment]
I have the same issue. Did you manage to find a fix? Thanks.

**Comment by programer786** [comment]
This error is shown by the newest version of anki on some of the interactive cards:
Found '⁨{{placeholder: String, editable: boolean}}⁩', but there is no field called '⁨ boolean⁩'
To solve it we need to replace this line on both the front and back templates:
`* @param {{placeholder: String, editable: boolean}} params`
with these 2 lines:

```
* @param {placeholder: String} params
* @param {editable: boolean} params
```
This solution was found by a user called "lydia" on another website
