### ISSUE TITLE
Found '⁨{{placeholder: String, editable: boolean}}⁩', but there is no field called '⁨ boolean⁩'

### ISSUE THREAD

**Issue by ghost** [qwiglydee/anki-interactive#30]
This error is shown by the newest version of anki on some of the interactive cards:
`Found '⁨{{placeholder: String, editable: boolean}}⁩', but there is no field called '⁨ boolean⁩'`
To solve it  we need to replace this line on both the front and back templates:
`* @param {{placeholder: String, editable: boolean}} params`
with these 2 lines:
```
* @param {placeholder: String} params
* @param {editable: boolean} params
```

This solution was found by a user called "lydia" on another website

**Comment by programer786** [comment]
[Interactive Demo.zip](https://github.com/qwiglydee/anki-interactive/files/6910199/Interactive.Demo.zip)
I have fixed the apkg here (and made it work with dark mode too by making the background of the boxes grey)
I had to put it in a zip file since github doesn't allow me to upload apkg files

**Comment by qwiglydee** [comment]
Thanks.

Fixed in new release.
